USE sibin;
CREATE TABLE CLASS
(RNO INT (5),
SNAME VARCHAR(15),
 MARKS INT(3));
 
 DESCRIBE CLASS;
 
 INSERT INTO CLASS VALUES(89,'SIBIN',100);
 
 INSERT INTO CLASS VALUES(90,'SREEJITH',95);

INSERT INTO CLASS VALUES(91,'SREELAKSHMI',99);
SELECT * FROM CLASS;
SELECT RNO FROM CLASS;
SELECT RNO RONO FROM CLASS;
